export const Users = [
    {
      id:1,
      profilePicture: "profilePictures/widow.jpg",
      username: "Natasha",
    },
    {
      id:2,
      profilePicture: "profilePictures/steve.jpg",
      username: "Steve Rogers",
    },
    {
      id:3,
      profilePicture: "profilePictures/strange.jpg",
      username: "Stephen strange",
    },
    {
      id:4,
      profilePicture: "profilePictures/ironman.jpg",
      username: "Robert Downey Junior",
    },
    {
      id:5,
      profilePicture: "profilePictures/peter.jpg",
      username: "Peter Parker",
    },
    {
      id:6,
      profilePicture: "profilePictures/loki.jpg",
      username: "Loki",
    },
    {
      id:7,
      profilePicture: "profilePictures/thanos.jpg",
      username: "Thanos",
    },
    {
      id:8,
      profilePicture: "profilePictures/capm.jpg",
      username: "captain marvel",
    },
    {
      id:9,
      profilePicture: "profilePictures/clint.jpg",
      username: "clint",
    },
    {
      id:10,
      profilePicture: "profilePictures/hulk.jpg",
      username: "Bruce Banner",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "posts/food.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "posts/food.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "posts/food.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "posts/food.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "posts/food.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "posts/food.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "posts/food.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "posts/food.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "posts/cast.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo:"posts/food.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];